extend type AuditLog {
  """
  ✨ Implicit foreign key field based on `AuditLog`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String @fdc_generated(from: "AuditLog.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Calculation {
  """
  ✨ Implicit foreign key field based on `Calculation`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Calculation.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Payment {
  """
  ✨ Implicit foreign key field based on `Payment`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Payment.user", purpose: IMPLICIT_REF_FIELD)
}
