extend type Query {
  """
  ✨ Look up a single `AuditLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  auditLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AuditLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AuditLog_FirstRow
  ): AuditLog @fdc_generated(from: "AuditLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Calculation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  calculation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Calculation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Calculation_FirstRow
  ): Calculation @fdc_generated(from: "Calculation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Payment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  payment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Payment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Payment_FirstRow
  ): Payment @fdc_generated(from: "Payment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WebhookLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  webhookLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WebhookLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WebhookLog_FirstRow
  ): WebhookLog @fdc_generated(from: "WebhookLog", purpose: QUERY_SINGLE)
  """
  ✨ List `AuditLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  auditLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: AuditLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AuditLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AuditLog_Having
  ): [AuditLog!]! @fdc_generated(from: "AuditLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Calculation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  calculations(
    """
    Filter condition to narrow down the query results.
    """
    where: Calculation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Calculation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Calculation_Having
  ): [Calculation!]! @fdc_generated(from: "Calculation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Payment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  payments(
    """
    Filter condition to narrow down the query results.
    """
    where: Payment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Payment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Payment_Having
  ): [Payment!]! @fdc_generated(from: "Payment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WebhookLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  webhookLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: WebhookLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WebhookLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WebhookLog_Having
  ): [WebhookLog!]! @fdc_generated(from: "WebhookLog", purpose: QUERY_MULTIPLE)
}
