extend type AuditLog {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "AuditLog", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `AuditLog` table.
  """
  _count: Int! @fdc_generated(from: "AuditLog.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `action` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  action_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.action", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `details` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  details_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.details", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `ipAddress` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ipAddress_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.ipAddress", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `userAgent` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userAgent_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.userAgent", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AuditLog` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AuditLog.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `AuditLog` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "AuditLog.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `AuditLog` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "AuditLog.createdAt", purpose: QUERY_MAX)
}
extend type Calculation {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Calculation", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Calculation` table.
  """
  _count: Int! @fdc_generated(from: "Calculation.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `baseCalculo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  baseCalculo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.baseCalculo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `dependentes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dependentes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.dependentes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `despesasEducacao` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  despesasEducacao_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.despesasEducacao", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `despesasMedicas` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  despesasMedicas_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.despesasMedicas", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `impostoDevido` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  impostoDevido_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.impostoDevido", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `inss` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  inss_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.inss", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `isLatest` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isLatest_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.isLatest", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `metodo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  metodo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.metodo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `pensaoAlimenticia` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  pensaoAlimenticia_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.pensaoAlimenticia", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `previdenciaPrivada` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  previdenciaPrivada_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.previdenciaPrivada", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `rendaBruta` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  rendaBruta_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.rendaBruta", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `totalDeducoes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  totalDeducoes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.totalDeducoes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Calculation` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Calculation.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `baseCalculo` field in the `Calculation` table.
  """
  baseCalculo_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.baseCalculo", purpose: QUERY_SUM)
  """
  ✨ Sum the `dependentes` field in the `Calculation` table.
  """
  dependentes_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Calculation.dependentes", purpose: QUERY_SUM)
  """
  ✨ Sum the `despesasEducacao` field in the `Calculation` table.
  """
  despesasEducacao_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.despesasEducacao", purpose: QUERY_SUM)
  """
  ✨ Sum the `despesasMedicas` field in the `Calculation` table.
  """
  despesasMedicas_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.despesasMedicas", purpose: QUERY_SUM)
  """
  ✨ Sum the `impostoDevido` field in the `Calculation` table.
  """
  impostoDevido_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.impostoDevido", purpose: QUERY_SUM)
  """
  ✨ Sum the `inss` field in the `Calculation` table.
  """
  inss_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.inss", purpose: QUERY_SUM)
  """
  ✨ Sum the `pensaoAlimenticia` field in the `Calculation` table.
  """
  pensaoAlimenticia_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.pensaoAlimenticia", purpose: QUERY_SUM)
  """
  ✨ Sum the `previdenciaPrivada` field in the `Calculation` table.
  """
  previdenciaPrivada_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.previdenciaPrivada", purpose: QUERY_SUM)
  """
  ✨ Sum the `rendaBruta` field in the `Calculation` table.
  """
  rendaBruta_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.rendaBruta", purpose: QUERY_SUM)
  """
  ✨ Sum the `totalDeducoes` field in the `Calculation` table.
  """
  totalDeducoes_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.totalDeducoes", purpose: QUERY_SUM)
  """
  ✨ Average the `baseCalculo` field in the `Calculation` table.
  """
  baseCalculo_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.baseCalculo", purpose: QUERY_AVG)
  """
  ✨ Average the `dependentes` field in the `Calculation` table.
  """
  dependentes_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.dependentes", purpose: QUERY_AVG)
  """
  ✨ Average the `despesasEducacao` field in the `Calculation` table.
  """
  despesasEducacao_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.despesasEducacao", purpose: QUERY_AVG)
  """
  ✨ Average the `despesasMedicas` field in the `Calculation` table.
  """
  despesasMedicas_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.despesasMedicas", purpose: QUERY_AVG)
  """
  ✨ Average the `impostoDevido` field in the `Calculation` table.
  """
  impostoDevido_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.impostoDevido", purpose: QUERY_AVG)
  """
  ✨ Average the `inss` field in the `Calculation` table.
  """
  inss_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.inss", purpose: QUERY_AVG)
  """
  ✨ Average the `pensaoAlimenticia` field in the `Calculation` table.
  """
  pensaoAlimenticia_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.pensaoAlimenticia", purpose: QUERY_AVG)
  """
  ✨ Average the `previdenciaPrivada` field in the `Calculation` table.
  """
  previdenciaPrivada_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.previdenciaPrivada", purpose: QUERY_AVG)
  """
  ✨ Average the `rendaBruta` field in the `Calculation` table.
  """
  rendaBruta_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.rendaBruta", purpose: QUERY_AVG)
  """
  ✨ Average the `totalDeducoes` field in the `Calculation` table.
  """
  totalDeducoes_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Calculation.totalDeducoes", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `baseCalculo` field in the `Calculation` table.
  """
  baseCalculo_min: Float @fdc_generated(from: "Calculation.baseCalculo", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Calculation` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Calculation.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `dependentes` field in the `Calculation` table.
  """
  dependentes_min: Int @fdc_generated(from: "Calculation.dependentes", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `despesasEducacao` field in the `Calculation` table.
  """
  despesasEducacao_min: Float @fdc_generated(from: "Calculation.despesasEducacao", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `despesasMedicas` field in the `Calculation` table.
  """
  despesasMedicas_min: Float @fdc_generated(from: "Calculation.despesasMedicas", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `impostoDevido` field in the `Calculation` table.
  """
  impostoDevido_min: Float @fdc_generated(from: "Calculation.impostoDevido", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `inss` field in the `Calculation` table.
  """
  inss_min: Float @fdc_generated(from: "Calculation.inss", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `pensaoAlimenticia` field in the `Calculation` table.
  """
  pensaoAlimenticia_min: Float @fdc_generated(from: "Calculation.pensaoAlimenticia", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `previdenciaPrivada` field in the `Calculation` table.
  """
  previdenciaPrivada_min: Float @fdc_generated(from: "Calculation.previdenciaPrivada", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `rendaBruta` field in the `Calculation` table.
  """
  rendaBruta_min: Float @fdc_generated(from: "Calculation.rendaBruta", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `totalDeducoes` field in the `Calculation` table.
  """
  totalDeducoes_min: Float @fdc_generated(from: "Calculation.totalDeducoes", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `baseCalculo` field in the `Calculation` table.
  """
  baseCalculo_max: Float @fdc_generated(from: "Calculation.baseCalculo", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Calculation` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Calculation.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `dependentes` field in the `Calculation` table.
  """
  dependentes_max: Int @fdc_generated(from: "Calculation.dependentes", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `despesasEducacao` field in the `Calculation` table.
  """
  despesasEducacao_max: Float @fdc_generated(from: "Calculation.despesasEducacao", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `despesasMedicas` field in the `Calculation` table.
  """
  despesasMedicas_max: Float @fdc_generated(from: "Calculation.despesasMedicas", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `impostoDevido` field in the `Calculation` table.
  """
  impostoDevido_max: Float @fdc_generated(from: "Calculation.impostoDevido", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `inss` field in the `Calculation` table.
  """
  inss_max: Float @fdc_generated(from: "Calculation.inss", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `pensaoAlimenticia` field in the `Calculation` table.
  """
  pensaoAlimenticia_max: Float @fdc_generated(from: "Calculation.pensaoAlimenticia", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `previdenciaPrivada` field in the `Calculation` table.
  """
  previdenciaPrivada_max: Float @fdc_generated(from: "Calculation.previdenciaPrivada", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `rendaBruta` field in the `Calculation` table.
  """
  rendaBruta_max: Float @fdc_generated(from: "Calculation.rendaBruta", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `totalDeducoes` field in the `Calculation` table.
  """
  totalDeducoes_max: Float @fdc_generated(from: "Calculation.totalDeducoes", purpose: QUERY_MAX)
}
extend type Payment {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Payment", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Payment` table.
  """
  _count: Int! @fdc_generated(from: "Payment.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `amount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  amount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.amount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `completedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  completedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.completedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `currency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.currency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `paymentMethod` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  paymentMethod_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.paymentMethod", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `stripePaymentIntentId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  stripePaymentIntentId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.stripePaymentIntentId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `stripeSessionId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  stripeSessionId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.stripeSessionId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Payment` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Payment.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `amount` field in the `Payment` table.
  """
  amount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Payment.amount", purpose: QUERY_SUM)
  """
  ✨ Average the `amount` field in the `Payment` table.
  """
  amount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Payment.amount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `amount` field in the `Payment` table.
  """
  amount_min: Int @fdc_generated(from: "Payment.amount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `completedAt` field in the `Payment` table.
  """
  completedAt_min: Timestamp @fdc_generated(from: "Payment.completedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Payment` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Payment.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `amount` field in the `Payment` table.
  """
  amount_max: Int @fdc_generated(from: "Payment.amount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `completedAt` field in the `Payment` table.
  """
  completedAt_max: Timestamp @fdc_generated(from: "Payment.completedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Payment` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Payment.createdAt", purpose: QUERY_MAX)
}
extend type User {
  """
  ✨ List `AuditLog` objects in a one-to-many relationship (where `AuditLog`.`user` is this object).
  """
  auditLogs_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: AuditLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AuditLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AuditLog_Having
  ): [AuditLog!]! @fdc_generated(from: "AuditLog.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Calculation` objects in a one-to-many relationship (where `Calculation`.`user` is this object).
  """
  calculations_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Calculation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Calculation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Calculation_Having
  ): [Calculation!]! @fdc_generated(from: "Calculation.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Payment` objects in a one-to-many relationship (where `Payment`.`user` is this object).
  """
  payments_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Payment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Payment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Payment_Having
  ): [Payment!]! @fdc_generated(from: "Payment.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `hasPaid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  hasPaid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.hasPaid", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `lastLogin` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastLogin_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.lastLogin", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `provider` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  provider_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.provider", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `stripeCustomerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  stripeCustomerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.stripeCustomerId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `lastLogin` field in the `User` table.
  """
  lastLogin_min: Timestamp @fdc_generated(from: "User.lastLogin", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `User` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "User.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `lastLogin` field in the `User` table.
  """
  lastLogin_max: Timestamp @fdc_generated(from: "User.lastLogin", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `User` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "User.updatedAt", purpose: QUERY_MAX)
}
